
const Products = [
    {
        src: "../../src/assets/images/01.png",
        alt: "Jean mujer azul",
        price: 29.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/02.png",
        alt: "2 Blusa mujer gris",
        price: 49.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/03.png",
        alt: "Chaqueta mujer lana",
        price: 59.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/04.png",
        alt: "Chompa mujer cuero negro",
        price: 95.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/05.png",
        alt: "Chompa hombre azul",
        price: 199.99,
        category: "ropa",
        gender: "man",
    },
    {
        src: "../../src/assets/images/06.png",
        alt: "Top mujer blanco",
        price: 24.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/07.png",
        alt: "Chaqueta hombre gris",
        price: 79.99,
        category: "ropa",
        gender: "male",
    },
    {
        src: "../../src/assets/images/08.png",
        alt: "Vestido mujer rojo",
        price: 59.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/09.png",
        alt: "Saco lana blanco",
        price: 69.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/10.png",
        alt: "Blazer mujer rosa",
        price: 42.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/11.png",
        alt: "Falda mujer blanca",
        price: 34.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/12.png",
        alt: "Blusa mujer blanca",
        price: 54.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/13.png",
        alt: "Blusa diseÃ±o mujer",
        price: 19.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/14.png",
        alt: "Chaleco mujer puntos",
        price: 22.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/15.png",
        alt: "Chaqueta mujer completa",
        price: 45.00,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/16.png",
        alt: "16 Botines mujer cafe",
        price: 28.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/17.png",
        alt: "Chompa deportiva hombre",
        price: 19.99,
        category: "ropa",
        gender: "man",
    },
    {
        src: "../../src/assets/images/18.png",
        alt: "Camiseta negra hombre",
        price: 39.99,
        category: "ropa",
        gender: "man",
    },
    {
        src: "../../src/assets/images/19.png",
        alt: "19 Saco cuello hombre",
        price: 87.99,
        category: "ropa",
        gender: "man",
    },
    {
        src: "../../src/assets/images/20.png",
        alt: "Licra mujer negra",
        price: 21.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "../../src/assets/images/21.png",
        alt: "Pulsera de Cuentas",
        price: 12.0,
        gender: "unisex",
        category: "accesorio",
        descripcion: "Pulsera artesanal de cuentas de madera.",
    },
    {
        src: "../../src/assets/images/22.png",
        alt: "Aretes Clasicos",
        price: 6.99,
        gender: "niño",
        category: "accesorio",
        descripcion: "Set de 5 pines con formas variadas.",
    },
    {
        src: "../../src/assets/images/23.png",
        alt: "Billetera de cuero",
        price: 60.0,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Billetera pequeña tipo cuero.",
    },
    {
        src: "../../src/assets/images/24.png",
        alt: "Bolso Cruzado",
        price: 60.0,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Bolso pequeño tipo bandolera.",
    },
    {
        src: "../../src/assets/images/25.png",
        alt: "Brazalete de Plata",
        price: 29.99,
        gender: "hombre",
        category: "accesorio",
        descripcion: "Brazalete doble con broche metálico.",
    },
    {
        src: "../../src/assets/images/26.png",
        alt: "Cinturón de Cuero",
        price: 45.99,
        gender: "hombre",
        category: "accesorio",
        descripcion: "Cinturón ajustable de cuero genuino.",
    },
    {
        src: "../../src/assets/images/27.png",
        alt: "Collar Minimalista",
        price: 15.0,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Collar sencillo con dije en forma de estrella.",
    },
    {
        src: "../../src/assets/images/28.png",
        alt: "Bufanda de Lino",
        price: 30.0,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Bufanda suave para el invierno.",
    },
    {
        src: "../../src/assets/images/29.png",
        alt: "Pareo de Playa",
        price: 27.0,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Pareo ligero ideal para la playa.",
    },
    {
        src: "../../src/assets/images/30.png",
        alt: "Sombrero Vaquero",
        price: 20.75,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Sombrero amplio para proteger del sol.",
    },
    {
        src: "../../src/assets/images/31.png",
        alt: "Muñequera de Oro",
        price: 89.5,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Muñequera de oro para fiestas.",
    },
    {
        src: "../../src/assets/images/32.png",
        alt: "Reloj clásico",
        price: 45.9,
        gender: "hombre",
        category: "accesorio",
        descripcion: "Reloj clásico para caballero.",
    },
    {
        src: "../../src/assets/images/33.png",
        alt: "Pañuelo Estampado",
        price: 10.5,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Pañuelo con diseño floral colorido.",
    },
    {
        src: "../../src/assets/images/34.png",
        alt: "Gorra Urbana",
        price: 25.5,
        gender: "unisex",
        category: "accesorio",
        descripcion: "Gorra de algodón con diseño urbano moderno.",
    },
    {
        src: "../../src/assets/images/35.png",
        alt: "Perfume D&G",
        price: 75.0,
        gender: "mujer",
        category: "accesorio",
        descripcion: "Perfume olor citrico y dulce.",
    },
    {
        src: "../../src/assets/images/36.png",
        alt: "Kit aretes nativos",
        price: 18.0,
        gender: "unisex",
        category: "accesorio",
        descripcion: "Pack de 3 pares de aretes nativos.",
    },
    {
        src: "../../src/assets/images/37.png",
        alt: "Lentes de Sol Retro",
        price: 55.0,
        gender: "unisex",
        category: "accesorio",
        descripcion: "Gafas de sol estilo retro con protección UV.",
    },
    {
        src: "../../src/assets/images/38.png",
        alt: "Prendedor de Invierno",
        price: 22.99,
        gender: "hombre",
        category: "accesorio",
        descripcion: "Prendedor para clima frío.",
    },
    {
        src: "../../src/assets/images/39.png",
        alt: "Riñonera Casual",
        price: 38.0,
        gender: "unisex",
        category: "accesorio",
        descripcion: "Riñonera con múltiples compartimientos.",
    },
    {
        src: "../../src/assets/images/40.png",
        alt: "Kit accesorios hombre ",
        price: 150.0,
        gender: "hombre",
        category: "accesorio",
        descripcion: "Pack de gafas, prendedores y reloj.",
    },
    {
        src: "../../src/assets/images/41.png",
        alt: "Balerina capuchina",
        price: 80.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/42.png",
        alt: "Bombardilo PRO X2",
        price: 90.00,
        category: "zapatos",
        gender: "male",
    },
    {
        src: "../../src/assets/images/43.png",
        alt: "Bombombini correrini",
        price: 70.00,
        category: "zapatos",
        gender: "male",
    },
    {
        src: "../../src/assets/images/44.png",
        alt: "Capuchino mountain",
        price: 85.00,
        category: "zapatos",
        gender: "male",
    },
    {
        src: "../../src/assets/images/45.png",
        alt: "Confortini zapatini",
        price: 93.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/46.png",
        alt: "Corredilo rosadino",
        price: 80.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/47.png",
        alt: "Crocodilo runner",
        price: 60.00,
        category: "zapatos",
        gender: "male",
    },
    {
        src: "../../src/assets/images/48.png",
        alt: "Elegantini botini",
        price: 55.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/49.png",
        alt: "Gangster footera",
        price: 70.00,
        category: "zapatos",
        gender: "male",
    },
    {
        src: "../../src/assets/images/50.png",
        alt: "Lirili larilá",
        price: 87.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/51.png",
        alt: "Ninivera nevada",
        price: 95.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/52.png",
        alt: "Sandalana payarana",
        price: 105.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/53.png",
        alt: "Saturnina balerina",
        price: 75.00,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "../../src/assets/images/54.png",
        alt: "Tralalero tralarun",
        price: 82.00,
        category: "zapatos",
        gender: "male",
    },
    {
        src: "../../src/assets/images/55.png",
        alt: "Trippi tropi",
        price: 89.00,
        category: "zapatos",
        gender: "male",
    },
]

export const getProductList = () => {
    return Products;
}
