const Products = [
    {
        src: "https://via.placeholder.com/200x200.png?text=Camisa+Blanca",
        alt: "Camisa blanca de algodón",
        price: 29.99,
        category: "ropa",
        gender: "man",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Vestido+Rojo",
        alt: "Vestido rojo elegante",
        price: 49.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Zapatillas+Deportivas",
        alt: "Zapatillas deportivas",
        price: 59.99,
        category: "zapatos",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Gorra+Negra",
        alt: "Gorra negra urbana",
        price: 15.99,
        category: "accesorios",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Jeans+Azules",
        alt: "Jeans azules clásicos",
        price: 39.99,
        category: "ropa",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Sandalias",
        alt: "Sandalias veraniegas",
        price: 24.99,
        category: "zapatos",
        gender: "female",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Bolso+de+Cuero",
        alt: "Bolso de cuero marrón",
        price: 79.99,
        category: "accesorios",
        gender: "female",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Chaqueta+Jean",
        alt: "Chaqueta de jean oversize",
        price: 59.99,
        category: "ropa",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Botines+Negros",
        alt: "Botines negros de cuero",
        price: 69.99,
        category: "zapatos",
        gender: "man",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Pulsera+Minimalista",
        alt: "Pulsera negra minimalista",
        price: 12.99,
        category: "accesorios",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Falda+Plisada",
        alt: "Falda plisada beige",
        price: 34.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Mocasines",
        alt: "Mocasines clásicos de vestir",
        price: 54.99,
        category: "zapatos",
        gender: "man",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Gafas+de+Sol",
        alt: "Gafas de sol polarizadas",
        price: 19.99,
        category: "accesorios",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Top+Deportivo",
        alt: "Top deportivo negro",
        price: 22.99,
        category: "ropa",
        gender: "female",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Tenis+Urbanos",
        alt: "Tenis blancos urbanos",
        price: 45.00,
        category: "zapatos",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Collar+de+Plata",
        alt: "Collar de plata con dije",
        price: 28.99,
        category: "accesorios",
        gender: "female",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Polo+Negro",
        alt: "Polo negro clásico",
        price: 19.99,
        category: "ropa",
        gender: "man",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Botas+de+Montaña",
        alt: "Botas resistentes de montaña",
        price: 89.99,
        category: "zapatos",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Bufanda+Gris",
        alt: "Bufanda gris de lana",
        price: 17.99,
        category: "accesorios",
        gender: "unisex",
    },
    {
        src: "https://via.placeholder.com/200x200.png?text=Camiseta+Oversize",
        alt: "Camiseta oversize con estampado",
        price: 21.99,
        category: "ropa",
        gender: "unisex",
    }

]